{% set name = "taurus_pyqtgraph" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2902169386d80177724f02f97022daf4ca18b74d38434049361d80d054c2ec55

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click
    - lxml
    - ply
    - pyqtgraph >=0.11
    - python >=3.6
    - taurus >=4.5.2
    - numpy <2.0

test:
  imports:
    - taurus_pyqtgraph
    - taurus_pyqtgraph.examples
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/taurus-org/taurus_pyqtgraph
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  summary: Taurus extension providing pyqtgraph-based widgets
  description: |
    taurus_pyqtgraph is an extension for the Taurus package.
    It adds the taurus.qt.qtgui.tpg submodule which provides pyqtgraph-based
    widgets.
  doc_url: http://taurus-scada.org
  dev_url: https://gitlab.com/taurus-org/taurus_pyqtgraph

extra:
  recipe-maintainers:
    - beenje
    - cpascual
